<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="DataGridView.aspx.cs" Inherits="DataGrid.DataGridView" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>DataGrid View</title>
    <script src="Scripts/jquery-3.4.1.js"></script>
    <script src="Scripts/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="https://cdn3.devexpress.com/jslib/16.2.15/js/dx.all.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn3.devexpress.com/jslib/16.2.15/css/dx.common.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn3.devexpress.com/jslib/16.2.15/css/dx.light.css" />
    <script src="Scripts/bootstrap.js"></script>
    <link href="Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <form runat="server">
    <asp:ScriptManager ID="ScriptManager1" runat="server">
</asp:ScriptManager>

            <asp:UpdatePanel ID="UpdatePanel1" runat="server">
    <ContentTemplate>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="true" AutoGenerateEditButton="true"  AutoGenerateDeleteButton="true" DataKeyNames="firstname" OnPageIndexChanging="GridView1_PageIndexChanging" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating">
              </asp:GridView>
          <table border="1">
            <tr>
                <td>
                    FirstNmae:<br />
                    <asp:TextBox ID="FirstNmae" runat="server" Width="140" />
                </td>
                <td>
                    LastName<br />
                    <asp:TextBox ID="LastName" runat="server" Width="140" />
                </td>
                  <td>
                    EmailId<br />
                    <asp:TextBox ID="EmailId" runat="server" Width="140" />
                </td>
                  <td>
                    Qualification<br />
                    <asp:TextBox ID="Qualification" runat="server" Width="140" />
                </td>
                  <td>
                    Ph.No<br />
                    <asp:TextBox ID="PhNo" runat="server" Width="140" />
                </td>
                  <td>
                    Country<br />
                    <asp:TextBox ID="Country" runat="server" Width="140" />
                </td>
                  <td>
                    State<br />
                    <asp:TextBox ID="State" runat="server" Width="140" />
                </td>
                  <td>
                    city<br />
                    <asp:TextBox ID="City" runat="server" Width="140" />
                </td>
                <td>
                    <asp:Button ID="btnAdd" runat="server" Text="Add" OnClick="Insert"  />
                </td>
            </tr>
        </table>
            </ContentTemplate>
</asp:UpdatePanel>
       </form>
</body>
</html>
